apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis-cache
metadata:
  name: redis-cache
commonLabels:
  app: redis-cache
resources:
- namespace.yaml
- deployment.yaml
- service.yaml