apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: centralized-log-es
  namespace: centralized-log
spec:
  version: 8.9.1
  nodeSets:
  - name: master-nodes
    count: 2
    config:
      node.store.allow_mmap: false
      node.roles:
      - master
  - name: data-nodes
    count: 2
    config:
      node.store.allow_mmap: false
      node.roles:
      - data