apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 5m
  chart:
    spec:
      chart: datadog
      version: 3.32.7
      sourceRef:
        kind: HelmRepository
        name: datadog-helm-repository
        namespace: flux-system
  values:
    datadog:
      logs:
        enabled: true
        containerCollectAll: true
      confd:
        openmetrics.yaml: |
          init_config:
          instances:
            - prometheus_url: https://foo-bar/metrics
              namespace: foo_bar
              ssl_ca_cert: false
              metrics:
                - foo

