apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-envoy-bootstrap
  namespace: gloo-system
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address: { address: 0.0.0.0, port_value: 8080 }
          filter_chains:
            - filters:
                - name: envoy.filters.http.lua
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                    inlineCode: |
                      function envoy_on_request(request_handle)
                        -- Add custom header
                        request_handle:headers():add("x-custom-header", "my-custom-value")
                      end
                    # Optional: You can also specify a Lua file
                    # inlineCode: ''
