apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gloo-system
  namespace: gloo-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gloo
      version: 1.17.15
      sourceRef:
        kind: HelmRepository
        name: solo-helm-repository
        namespace: gloo-system
  values:
    discovery:
      enabled: false

