apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gloo-system
metadata:
  name: gloo-system
commonLabels:
  app: gloo-system
resources:
- namespace.yaml
- helmRepository.yaml
- helmRelease.yaml
- gateway.yaml
- upstreams.yaml
- virtualServices.yaml
- settings.yaml