
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: auth-server-upstream
  namespace: gloo-system
spec:
  discoveryMetadata: {}
  kube:
    selector:
      app: auth-server
    serviceName: auth-server-service
    serviceNamespace:  gloo-system
    servicePort: 8000
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: calculator
  name: calculator-upstream
  namespace: gloo-system
spec:
  discoveryMetadata: {}
  kube:
    selector:
      app: calculator
    serviceName: calculator-service
    serviceNamespace: calculator
    servicePort: 8080
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: 1
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: calculator
  name: calculator-a-upstream
  namespace: gloo-system
spec:
  discoveryMetadata: {}
  kube:
    selector:
      app: calculator
    serviceName: calculator-service
    serviceNamespace: calculator
    servicePort: 8080
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: 1
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: calculator
  name: calculator-b-upstream
  namespace: gloo-system
spec:
  discoveryMetadata: {}
  kube:
    selector:
      app: calculator
    serviceName: calculator-service
    serviceNamespace: calculator
    servicePort: 8080
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: 1
      