
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: auth-server-upstream
  namespace: gloo-system
spec:
  discoveryMetadata: {}
  kube:
    selector:
      app: auth-server
    serviceName: auth-server-service
    serviceNamespace:  gloo-system
    servicePort: 8000
---