kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080