apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-core
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.5.6
      sourceRef:
        kind: HelmRepository
        name: bitnami-helm-repository
  values:
    auth:
      username: "postgresqlcore"
      password: "postgresqlcorepassword"
      database: "postgresqlcore"
