apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: datadog-helm-repository
  namespace: flux-system
spec:
  interval: 5m
  url: https://helm.datadoghq.com
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gloo-helm-repository
  namespace: flux-system
spec:
  interval: 5m
  url: https://storage.googleapis.com/solo-public-helm