apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flagger
metadata:
  name: flagger
commonLabels:
  app: flagger
resources:
- namespace.yaml
- helmRepository.yaml
- helmRelease.yaml