apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: redis-cache
commonLabels:
  app: redis-cache
helmCharts:
- name: redis
  repo: https://charts.bitnami.com/bitnami
  version: 7.0.11
  valuesFile: values.yaml
  # additionalValuesFiles:
  # - values-file-1.yml
  # - values-file-2.yml