apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  namespace: calculator
  labels:
    app: calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      appName: calculator
  template:
    metadata:
      labels:
        appName: calculator
    spec:
      containers:
      - name: go-calculator
        image: syafdia/go-calculator:latest
        ports:
        - containerPort: 8080
        env:
        - name: MAX_NUMBER
          valueFrom:
            configMapKeyRef:
              name: calculator-configmap
              key: max_number
        - name: REDIS_URL
          value: 'redis://redis-service.redis-cache.svc.cluster.local:6379'