apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  namespace: calculator
  labels:
    app: calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: go-calculator
        image: syafdia/go-calculator:latest
        ports:
        - containerPort: 8080
        env:
        - name: MAX_NUMBER
          valueFrom:
            configMapKeyRef:
              name: calculator-configmap
              key: max_number