apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calculator
metadata:
  name: calculator
commonLabels:
  app: calculator
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- configMap.yaml