kind: Service
apiVersion: v1
metadata:
  name: calculator-service
  namespace: calculator
spec:
  type: LoadBalancer
  selector:
    appName: calculator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080