// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repo/resource_repo.go

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entity "github.com/syafdia/xaam/internal/domain/entity"
	reflect "reflect"
)

// MockResourceRepo is a mock of ResourceRepo interface
type MockResourceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockResourceRepoMockRecorder
}

// MockResourceRepoMockRecorder is the mock recorder for MockResourceRepo
type MockResourceRepoMockRecorder struct {
	mock *MockResourceRepo
}

// NewMockResourceRepo creates a new mock instance
func NewMockResourceRepo(ctrl *gomock.Controller) *MockResourceRepo {
	mock := &MockResourceRepo{ctrl: ctrl}
	mock.recorder = &MockResourceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockResourceRepo) EXPECT() *MockResourceRepoMockRecorder {
	return m.recorder
}

// FindMultipleByIDs mocks base method
func (m *MockResourceRepo) FindMultipleByIDs(ctx context.Context, ids []int64) (map[int64]entity.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMultipleByIDs", ctx, ids)
	ret0, _ := ret[0].(map[int64]entity.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMultipleByIDs indicates an expected call of FindMultipleByIDs
func (mr *MockResourceRepoMockRecorder) FindMultipleByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMultipleByIDs", reflect.TypeOf((*MockResourceRepo)(nil).FindMultipleByIDs), ctx, ids)
}

// FindMultipleByNames mocks base method
func (m *MockResourceRepo) FindMultipleByNames(ctx context.Context, names []string) (map[string]entity.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMultipleByNames", ctx, names)
	ret0, _ := ret[0].(map[string]entity.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMultipleByNames indicates an expected call of FindMultipleByNames
func (mr *MockResourceRepoMockRecorder) FindMultipleByNames(ctx, names interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMultipleByNames", reflect.TypeOf((*MockResourceRepo)(nil).FindMultipleByNames), ctx, names)
}
